version: "3.8"

services:
  db_postgres:
    image: "postgres:13-alpine"
    container_name: db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"
  shortener:
    container_name: shortener_service
    image: "gingin3203/shortener:0.0.1"
    build:
      context: .
      dockerfile: shortener.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db_postgres
