service:
  name: url_shortener
  minUrlEncodingLength: 5
  shortUrlDomainName: o.co
http:
  port: 8080
  requestTimeoutSeconds: 20
storage: postgres # [memory, postgres]
postgres:
  url: "postgresql://postgres:postgres@db_postgres:5432/shortener"
