service:
  name: url_shortener
  urlEncodingLength: 5
http:
  port: 8080
  requestTimeoutSeconds: 5
storage: postgres # [memory, postgres]
postgres:
  requestTimeoutSeconds: 3
  port: 5432
  user: postgres
  password: postgres
  database: shortener
memory:
  requestTimeoutSeconds: 2
